export enum IconType {
  CloseIcon = 'CloseIcon',
  DatepickerIcon = 'DatepickerIcon',
  DealCompleted = 'DealCompleted',
  DocumentIcon = 'DocumentIcon',
  DownArrow = 'DownArrow',
  DownloadIcon = 'DownloadIcon',
  EnergyIcon = 'EnergyIcon',
  InfoIcon = 'InfoIcon',
  GasIcon = 'GasIcon',
  InternetIcon = 'InternetIcon',
  MenuIcon = 'MenuIcon',
  MoreIcon = 'MoreIcon',
  OngoingIcon = 'OngoingIcon',
  RightChevronIcon = 'RightChevronIcon',
  SavingsIcon = 'SavingsIcon',
  StarIcon = 'StarIcon',
  TelecomIcon = 'TelecomIcon',
  TreeIcon = 'TreeIcon',
  UpArrow = 'UpArrow',
  WaterIcon = 'WaterIcon',
}
